[package]
name = "inserta_partidas"
version = "0.1.0"
authors = ["calvicius"]

[dependencies]
regex = "1.0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
num_cpus = "*"
threadpool = "*"

[dependencies.rusqlite]
version = "0.16.0"
features = ["bundled"]